name: Java

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  check-go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
    - uses: actions/upload-artifact@v3
      with:
        name: Package
        path: build/libs

#    - name: Build
#      env:
#        CGO_ENABLED: "0"
#        GOOS: "linux"
#      run: cd ./app && go build -o ./.bin/redis-cache-example -v ./cmd/redis-cache-example/main.go
#
#    - name: Upload Go build results
#      uses: actions/upload-artifact@v3
#      with:
#        name: linux-binary
#        path: ./app/.bin/redis-cache-example
#        retention-days: 90

